# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Release

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        default_bump: "patch"
        tag_prefix: "v"
    - name: Build
      run: |
        ./gradlew cleanSwiftPM
        ./gradlew createXCFramework
    - name: Update SwiftPM
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -M "Update SwiftPM"
    - name: Release
      uses: softprops/action-gh-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        name: ${{ steps.tag_version.outputs.new_tag }}
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true
#        files: shared/build/swiftPM/SampleKMMLibrary.xcframework.zip
